apiVersion: v1
kind: Secret
metadata:
    name: github-tamagotchi-secrets
    namespace: nijmegen-testing
type: Opaque
stringData:
    database-url: ENC[AES256_GCM,data:7UHrOlLvy2W/LhcmE93PfARhhe2N8nN7fD4GuJWxoOXavZB/5BeMfbvUIiA735nW2nzY/Tc3IwJaKWSsy2jlrIUXRb33,iv:5gkmB9WLRTuDUnT+LXlKJbkTtAW1n/iKtrovtc29vrc=,tag:VopqOzmR2t6Y2B5wgDF4iw==,type:str]
    github-token: ENC[AES256_GCM,data:HLf8tHS2EwwcPYYZdTKJHmJIdCo/fUzXEwvOfJP/+Mie6j6b16GtOeuoaMzxpvHGyF4SMy4DtMtYx1l/uZaY+PGR+tgKrjIdeKZg1tTpi4hPc5oQq62Ua+Hpje2f,iv:XtEwdEusYFfj7Ec+QE4+K6wZ7KwZ9F2Fc8licfPDqdY=,tag:ApXWIA/QMOwZ+UzPRHoo5g==,type:str]
    openrouter-api-key: ENC[AES256_GCM,data:nUegZWmz69kW2jj0XQS8DJFoAsp5hVCOBv4Qgj2Nt9nvsITQMkyBa+mWDBNInbYYOOa2V/QMS26THgxVe72imSYG8mG+RBOFvg==,iv:ZswV5IhApIN5ovugrfXH9k0TmkHhdlFTRvPMNQMRMp4=,tag:ylsDtlxkc3CfIBpP7KJG7A==,type:str]
    minio-access-key: ENC[AES256_GCM,data:8p6g3IXEBmDlg8QMasvK,iv:v+U99547alXHhdHIpBUxRZ0j/s8A+rfLBUuuf2Ujpd0=,tag:zKyuRzZWo8yXKShIef9XnA==,type:str]
    minio-secret-key: ENC[AES256_GCM,data:jMAfe2juwTFgeSHVmupL5siJ9S4fCA==,iv:X5ZmZd8sxw1J9KcPrG9nAztTsemEbRt8MUGoOBeHx7s=,tag:Ft88KDGKXtL/hR/rbwp36A==,type:str]
    github-oauth-client-id: ENC[AES256_GCM,data:SIzZrG06mTX5Ae1kI9EgLVcJlew=,iv:48oKUKrpq1EdqFOK9UIPGVcRf6paAY1z9FIuoOaolg8=,tag:s7EmvhHhIAwI6Hm6oxO8rA==,type:str]
    github-oauth-client-secret: ENC[AES256_GCM,data:iLjOrAaYGdC1B2ltKvieORZaPHbjhPdnTvjENy1myEv0Byp6B+LYLA==,iv:CCKXJ/hz5HAJfUzdnDYwcAS1JGo0ONfOAWjOiirLXN0=,tag:6Pc2Gl4uwJ2Fij/jeqA3Nw==,type:str]
    jwt-secret-key: ENC[AES256_GCM,data:kmsGQfkn9vs5IA9GFr1GN+H3OcIAqFtSx0rLz7r5xbPE5uVDA39IoV02K4+7kigpGLiaQbEI2MkjVlejGVAAew==,iv:dcgwxpPGz4gYnDGrlevWrCy0EzFzw4uBFls+SgdNGrU=,tag:UD6J7Ix7IIC+66XzIa2G2A==,type:str]
    token-encryption-key: ENC[AES256_GCM,data:0m1dtIRjFwf0Jg0wre7tEYprCqsq3zH2sxm0oFaLSqkViAVQ4NRhlrSDjnw=,iv:90a7i7J6UslTzDTCeOFZxcnu/ynArImnA5ri7KwLdi0=,tag:3pXkH9y7JphdG08b6i9Cpw==,type:str]
    sentry-dsn: ENC[AES256_GCM,data:DXaCZ7lKE5y+AvxgQ1KisKfYHJ7lrLu6Ge7OcoJe8dcmE8dmqEXMpWdB/XZlxK0e4aYuRPKa2unoqqnvM49TKp8JXuqLNuOHMfSo8i6+GUzvi0y4NHPuN5hORy+6UTU=,iv:alspJm21JIuivinDptr+eE31me9MyN/bM0Q7YSG1oeM=,tag:lv94Iz3YKRpXaW9HSYX+Kg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18zj2snpz4mvhzrfyhtdg2mjgzk3qaqcxc0yspadzruz2sw5qqdvq0mh3ym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVazByQmNOUUhZZUNHSldO
            ZGN3QTRsY0thaW02Z2ZWM2U2VmpoeVppMFNjCjgxWXZJSEkzVzc5c1VGMjR4RTJl
            Y20rZmpOdU8rVEdGSXRNS29IK0FVUlUKLS0tIDVnZktuWHBOeXpmQ3MzSFZEdWh1
            UUh4ZFFOM1pOYkt2MENER0prYzlaSjAKn60fnvXsOwj9gOrgm+7rmhCf58BQUdMU
            a+dndhVM6i6OyyqzQlp7tCCIGyPldIqfx8EkHw6wLrgfCudAFlTkug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T12:57:57Z"
    mac: ENC[AES256_GCM,data:MdBU5+u+BIJb5rwsLnaiErVqMB0cPJ1EQm/TjQm2oEmdHXWJIBtGYnj+rIr+0duLzlOG2UD+3sjdJ3ICUeK5NNrb8eJpEnUaRMKZzZBQ8ebC+vhlPnhsmdRRn+GPCYzNp/UBpu0zt86dCcVQu1Xq8rq3n3CAKgfHvMTSEn+muHU=,iv:c78cDgpUNWqsNa1LNmdkAo7+nVbGhN/MYpah8pma9j4=,tag:J8V25msHT08uJJgmcMaCDw==,type:str]
    pgp: []
    encrypted_regex: ^stringData$
    version: 3.9.4
