apiVersion: v1
kind: Secret
metadata:
    name: github-tamagotchi-secrets
    namespace: nijmegen-testing
type: Opaque
stringData:
    database-url: ENC[AES256_GCM,data:MEkcqkqYT/17IxKd5HjkGbMozn+s8XRa8h+49f5xUeeF7fh0bsGmCBjs2LY3IgWZ+vtt2W8MAsvpe9C7kIMxsuDlsmja,iv:AnQ71vRxbgLqHzq2g2ITEgeFtW4KRakQSfPZFW5nzb0=,tag:mI53fErwrBWFC4bObmp6tg==,type:str]
    github-token: ENC[AES256_GCM,data:b4Ks6Y94xHV4tN8tzCJi4QkgoYdTs4A2LMPHGZ2SPCFINfvKBg8Dq+UQ81NxkptqZrktlWsJPHEQdcRQAxiH3ab4oX+bD4GYuTttoTFd8zcycxKC7jrR+/hRQrVK,iv:23yP0TuCXLaDjOhvqDf3gQZ0DqlbnihtrlNzYqNy0+o=,tag:lf0AxrAxfUXrDuOSmIANjw==,type:str]
    openrouter-api-key: ENC[AES256_GCM,data:5q8ijjJBYouUYgsDEitECYAqyJABGsJmu7Y+2LHAkW2vDxALiqNytGgQ0mHWzdXA0uQ07AiXS8EmLo9lnmbjgEWx0l4T1jXLPg==,iv:2aRrKvzTPQjP5ZpC/yHY25ZMVoszCBw4irmPTRY85Po=,tag:+YxaCFE2CC5TnOmFs5j/Yg==,type:str]
    minio-access-key: ENC[AES256_GCM,data:K2wIFOd2PQvTweJxQdct,iv:JNPbvG3Qn9XeNVGqErQWiYYBkFXdpzwRKaPKdoF6qa0=,tag:NeEuluPWTZn/OsbBtnbbsQ==,type:str]
    minio-secret-key: ENC[AES256_GCM,data:+lx1hhR/exWKCcQ4OlP4ujHLLN/2mA==,iv:y4AFtStT27NyvbovHTPDIyGE2GRTibqfD/cYYLF8qJE=,tag:jRsnA4Wum9KTTcpVkUaHHw==,type:str]
    github-oauth-client-id: ENC[AES256_GCM,data:tmEpTB37a62nCo74RGJ2udujQN8=,iv:yFfD+EDihqn4BlMF2O13hiS1TFKL6aTy1lVY5t7dYts=,tag:PuHkGm16Lzf9CSMrx5GicA==,type:str]
    github-oauth-client-secret: ENC[AES256_GCM,data:GDim0H27MwfCrkuhM37EB6Emf0/ZNdS4k4LJiLnLKkiMcaCIC1MY2A==,iv:EfAbmOlq3dGFGkwsKfT0IzJuU8Bs3YAXbh2j2Oes7hY=,tag:SKPzSHbc3x7Y5jFvIiUqCQ==,type:str]
    jwt-secret-key: ENC[AES256_GCM,data:H2tmcAGbil+rBRNduIZ4AVSTAjOS2JKOqhCAtxrkGNjwvP9yLReQ/HqOwD3vlh4fkTZyoYUh/cj4VS8UxaOtAA==,iv:jJJ9ZLYZN6mh/uMuOBZ7N8YtXPqVtdCcs0sZa2d3LvQ=,tag:HShdSstyMthLzALF/9WFdw==,type:str]
    token-encryption-key: ENC[AES256_GCM,data:8Zl6fOHPNRAEYGktHQ6hbd5BDbuqWF9DkiQRGNkjnEDyG98HSUuzRpZ0pbA=,iv:YLWMyFKB2JPsC0JTGOBv7/t1Sou+hJCKIB1cZVlorqM=,tag:s61B6JqELN2x+quaLHWBiQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18zj2snpz4mvhzrfyhtdg2mjgzk3qaqcxc0yspadzruz2sw5qqdvq0mh3ym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoOFFBUDVGQU5LbUN6Q3l1
            MWp6TWk2VGdXTUVISnNYRlVvZ09LeE1UYVR3CjJxSjZlc2ErTFFQQS9LSXZMMFcx
            N2xsbUxIQzRxVFhVN2Y4NTBNKzhPYU0KLS0tIHlsaFFKTDJISk5tT242bU8za29N
            aVhzRUtyQkRRNEtYenpTT2dZNHdsMFUKa5i6peBahj1tg2yqJI91kqoHLIgRRYYw
            yvNrGvwnx3HnAaaenXxtrtpbF1kK0+zjRJ++bbAKfoRyXrC8/qWA3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T13:52:42Z"
    mac: ENC[AES256_GCM,data:GM/Eme7JMGoeo2FulT03fGRVYLj+9iRzO2ZujgNaZZ45mhYIVmZ0I/IXyYoxDbnTUfnXRia8tWLysfnyILZntkoaBU8CJvNQEM10ZAImdFiODGhaKwOPC3m5pIXOEk7Fq3yEpJXqpCfyIoCG6OhwSWBxWd3aVMGN2btLvb69bj8=,iv:vL/bx0iIubvPQq1l6SetGxF8uvMgDaDn9wzJ0Iab9+k=,tag:jDa3AuLSFCyzn/6xzn7UmQ==,type:str]
    pgp: []
    encrypted_regex: ^stringData$
    version: 3.9.4
