apiVersion: v1
kind: Secret
metadata:
    name: github-tamagotchi-secrets
    namespace: nijmegen-testing
type: Opaque
stringData:
    database-url: ENC[AES256_GCM,data:bX/K6n6X+MK/hZRpaJt80plENgv+W6AQDtbpLKCsiIIDf6899huTPBImgosp9+8dY5cxm/RZvqdrj4QcwbF4DfCwK6tV,iv:kOE85Iv6cH15kd5WCEvpPSYdBSNKm17P2r5ZjAkLWCE=,tag:EsSDRNzyG/EDnopFaWtwnw==,type:str]
    github-token: ENC[AES256_GCM,data:Rm/dpi9Dtziy8nJ6ROT+2GVv4BT+eM7hZ68oZNYC6FMoC13W35G1XjbZmdJKeJhM34ctbxieag7Kp+aSJ8WS5DT8dM9kAVNiDI7Z72/nFjTin9AvlGDD3tyjhaDF,iv:4v0SbdjfXQLKme0DeB9YOyw7CEqZSuPZVY/mX8XQkd8=,tag:eHQrxeKi15fWK5WoSBI71w==,type:str]
    openrouter-api-key: ENC[AES256_GCM,data:PUVWNgKx2aCgBdlMjnTwZcGLFj+1mKmYzfeMhwiKafSnqHkS5PBHRioxKu75N0qFYmoKvpiS6yal1QwijSutH1GixT8glqpu5g==,iv:hyxonta5xu2VoSkqgWfkMKa4p8NnxBKWak0Af3F9niI=,tag:81FhJtKH0BT1gqOKYrpR2g==,type:str]
    minio-access-key: ENC[AES256_GCM,data:/2JbITAPtbDfiBqztJYM,iv:O1TwjJEWd2jg/+KqVIDMFZO3apcYVPDTveUjS8mE1VI=,tag:5Ro9517Hl/6aBJbrh8Uv9Q==,type:str]
    minio-secret-key: ENC[AES256_GCM,data:OoNi4wAdiNUY2NkwrUOQxnpehiOdNw==,iv:RM7NvJRgokrroWZQflWr27/tH70mb2nbjvyu/CDNavU=,tag:6bKh1zt2tIzMMtFR0TZ0sA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18zj2snpz4mvhzrfyhtdg2mjgzk3qaqcxc0yspadzruz2sw5qqdvq0mh3ym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOHJjMXhMdm8yNm0vNkJE
            SEs1STBNUWdyUVFxcURncllLdzYwbENwMkFJCmxtNk9PUFBHLzkyNHNyQk11cXp0
            ZDN4cnI3L1RjMUlnb0FIbzZ4ekQzeFkKLS0tIG5kRnpqdWhmTXpmNVJSaHMxWjJm
            b2dOYnBNNUlnenVvbXZSUXk5OWYvTTQKgFQz3yxp3aiYCEAKDnDoLnHenkw2wkMW
            ZmPI/futxrmqOmmeQoGvcNoC5td9qpjF1jv3LnZb3dUajLz/Gu9oZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T14:17:20Z"
    mac: ENC[AES256_GCM,data:sCkwHS91Wy08BAORYaxdwr7A+y0P5N1UdYO9lrIL9PDIQAKQcR/rKMSbW38TYIEIkERb1i1Q9KjLSxHIgwDpP3OJfvOCIaM0y70T2g3ApFZi5itdvHgV9h/jicn6L+8o7khkCUIMJdS4JquhXNP3VXkUfBSytyxiUo96EEEJBYw=,iv:BdmuYLi8HhxXpdQFV9/Yz2vC/EzY2vLksobCags6LfU=,tag:DmQMTj93XCWwV8dWWlRplQ==,type:str]
    pgp: []
    encrypted_regex: ^stringData$
    version: 3.9.4
