apiVersion: v1
kind: Service
metadata:
  name: github-tamagotchi
  namespace: tama-prod
spec:
  selector:
    app: github-tamagotchi
    version: blue
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
